CUDA_VISIBLE_DEVICES=0 python src/gen_sd_v12_freeu_coco.py \
                        --pipeline-ckpt="checkpoints/stable-diffusion-2-1-base"  \
                        --save-dir="main_exps_fid/coco_FreeU_gen_sdv21" \
                        --precision="fp16" \
                        --json="data/coco_mapping_clean.json" \
                        --seed=2710 \
                        --inference-steps=25 \
                        --guidance-scale=7.5 \
                        --start=0 \
                        --end=-1 \
                        --batch-size 32 \
                        --b1=1.4 \
                        --b2=1.6 \
                        --s1=0.9 \
                        --s2=0.2 \
